version: '3.1'
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: True
  redis:
    image: redis
    ports:
      - 6379:6379
  es:
    image: elasticsearch:8.11.3
    environment:
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "password"
    ports:
      - 9200:9200
      - 9300:9300